version: '3.8'

services:
  linguaai-api:
    build:
      context: .
      dockerfile: LinguaAI.Api/Dockerfile
    ports:
      - "5278:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  linguaai-web:
    build:
      context: .
      dockerfile: LinguaAI.Web/Dockerfile
    ports:
      - "5262:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiSettings__BaseUrl=http://linguaai-api:8080
    depends_on:
      - linguaai-api
    restart: always
